export default{
    flexGeral:1,
    alignGeral:'center',
    //TelaComeco
    telaPadding:10,
    tituloFont:20,
    tituloMargin:10,
    //ContatoInput
    viewFlex:'row',
    viewJustify:'space-between',
    viewHeight:50,
    viewMargin:20,
    inputWidth:'40%',
    inputBorder:1,
    inputPadding:2,
    inputBorderR:5,
    //ContatoItem
    itemWidth:300,
    itemMaxW:'100%',
    //Cartao
    cartaoShadowR:6,
    cartaoShadowO:0.32,
    cartaoElevation:4,
    cartaoPadding:15,
    cartaoBorder:15,
    //Cabecalho
    cabecalhoWidth:'100%',
    cabecalhoHeigth:95,
    cabecalhoPadding:40,
    cabecalhoJustify:'center',
    tituloFontS:22
}